source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

group :doc do

  gem 'sdoc', require: false
end

gem 'bcrypt', '~> 3.1.7'

gem 'bootstrap-sass', '3.1.1.0'
gem 'rabl', '0.9.3'
gem 'warden'
gem 'pry'

gem 'subscribem', path: '../subscribem'

group :development, :test do
  gem 'rspec-rails', '3.0.1'
  gem 'capybara', '2.3.0'
  gem 'factory_girl', '4.4.0'
end